version: '3.8'

services:
  app:
    image: openjdk:11
    container_name: coworking_app
    volumes:
      - ./src/main:/app
    working_dir: /app
    command: ["./mvnw", "spring-boot:run"]
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: coworking_db
    environment:
      POSTGRES_DB: coworking
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: